### ISSUE TITLE
Template in online platform Overleaf

### ISSUE THREAD

**Issue by Soumyabrata** [dnl-blkv/mcdowell-cv#7]
Hello,
Nice template, but it seems there is a problem in compiling it in online LaTeX platform (Overleaf). [Here](https://www.overleaf.com/12266154sqpshxfjmqdc) is the overleaf edit link.
Any suggestions in solving this?

**Comment by brainwave** [comment]
The issue is stemming because the style template (mcdowellcv.cls) tries to check for which OS is running to apply platform specific spacing in the document. Removal of 
\usepackage{ifplatform} from line 70 fixes the error in overleaf. I'm adding some finishing touches, should soon have a template that works on overleaf.

**Comment by brainwave** [comment]
@Soumyabrata  - I have modified the class definitions to be overleaf compatible on an ad-hoc basis. Feel free to use them.

https://github.com/brainwave/mcdowell-cv/tree/master

**Comment by Soumyabrata** [comment]
Brilliant - the modified version works great! 
I'd suggest to commit another change in the corresponding tex file - 
Change the line with` \documentclass[]{mcdowellcv} `to` \documentclass[]{mcdowellcv_modified}` to use the new corresponding class file. It will then compile successfully.

**Comment by brainwave** [comment]
@Soumyabrata Thanks for the suggestion - I have committed the changes (and renamed mcdowellcv_modified to just mcdowell.cls to avoid any confusion).
